import { describe, expect, it } from 'vitest';
import { MOTOR_DB, hasMassData } from './motorDb.js';
import { samplesToMotorSpec } from './thrustcurve.js';

/**
 * Data-integrity guard over the committed motors.json snapshot.
 *
 * The bundled catalog is generated by scripts/fetch-motor-db.mjs from
 * thrustcurve.org, whose entries are not uniformly populated. Motors with no
 * published loaded/propellant weight (or with propellant > loaded) produce NaN
 * or negative motor masses; before v0.053 those reached the TeaVM kernel and
 * came back as "The number NaN cannot be converted to a BigInt", blanking the
 * user's whole design. These tests pin the two halves of the fix so a future DB
 * refresh cannot quietly reintroduce it.
 */
describe('bundled motor database integrity', () => {
  const unusable = MOTOR_DB.filter((m) => !hasMassData(m));

  it('flags every entry whose published weights cannot yield a valid mass curve', () => {
    // Not an assertion that the count is zero — the catalog genuinely has gaps,
    // and we list those motors on purpose. What matters is that hasMassData
    // catches all three failure shapes.
    for (const m of unusable) {
      const bad =
        !Number.isFinite(m.totalWeightG) ||
        !Number.isFinite(m.propWeightG) ||
        m.propWeightG > m.totalWeightG;
      expect(bad, `${m.designation} was flagged but looks fine`).toBe(true);
    }
    // Sanity: the snapshot this guard was written against.
    expect(unusable.length).toBeGreaterThan(0);
    expect(unusable.length).toBeLessThan(MOTOR_DB.length * 0.25);
  });

  it('every motor that passes hasMassData builds a finite, non-negative mass curve', () => {
    const samples = [
      { time: 0, thrust: 0 },
      { time: 0.5, thrust: 10 },
      { time: 1, thrust: 0 },
    ];
    for (const m of MOTOR_DB.filter(hasMassData)) {
      const spec = samplesToMotorSpec(m, samples, 5);
      expect(spec.masses.every(Number.isFinite), `${m.designation}: non-finite mass`).toBe(true);
      expect(spec.masses.every((x) => x >= 0), `${m.designation}: negative mass`).toBe(true);
    }
  });

  it('refuses an entry with missing weights instead of producing NaN masses', () => {
    const broken = { ...MOTOR_DB[0]!, totalWeightG: undefined as unknown as number };
    expect(() => samplesToMotorSpec(broken, [{ time: 0, thrust: 1 }], 5)).toThrow(
      /publishes no loaded\/propellant weight/,
    );
  });

  it('refuses an entry with more propellant than loaded mass', () => {
    const broken = { ...MOTOR_DB[0]!, totalWeightG: 52, propWeightG: 104 };
    expect(() => samplesToMotorSpec(broken, [{ time: 0, thrust: 1 }], 5)).toThrow(
      /more propellant/,
    );
  });
});
