import type { ComponentNode, ComponentType } from '@online-openrocket/engine';

/**
 * Component preset database (openrocket-database .orc files → presets.json,
 * regenerated by scripts/fetch-component-presets.mjs; all SI). The bundle is
 * ~1.3 MB so it loads lazily on first use. User presets imported from CSV
 * are stored in localStorage and merged in.
 */

export interface Preset {
  kind: string;
  manufacturer: string;
  partNo: string;
  description: string;
  material?: { name: string; type: string; density: number };
  lineMaterial?: { name: string; type: string; density: number };
  mass?: number;
  [dim: string]: unknown;
}

/** .orc kind → editor component type. */
export const KIND_FOR_TYPE: Partial<Record<ComponentType, string>> = {
  bodytube: 'BodyTube',
  nosecone: 'NoseCone',
  transition: 'Transition',
  centeringring: 'CenteringRing',
  tubecoupler: 'TubeCoupler',
  bulkhead: 'BulkHead',
  engineblock: 'EngineBlock',
  launchlug: 'LaunchLug',
  parachute: 'Parachute',
  streamer: 'Streamer',
};

let bundled: Preset[] | null = null;

export async function loadPresets(): Promise<Preset[]> {
  if (!bundled) {
    const mod = await import('../data/presets.json');
    bundled = (mod.default as { presets: Preset[] }).presets;
  }
  return [...bundled, ...loadCustomPresets()];
}

const CUSTOM_KEY = 'online-openrocket.custom-presets.v1';

export function loadCustomPresets(): Preset[] {
  try {
    const raw = localStorage.getItem(CUSTOM_KEY);
    return raw ? (JSON.parse(raw) as Preset[]) : [];
  } catch {
    return [];
  }
}

export function saveCustomPresets(presets: Preset[]): void {
  localStorage.setItem(CUSTOM_KEY, JSON.stringify(presets));
}

const n = (p: Preset, key: string): number | undefined =>
  typeof p[key] === 'number' ? (p[key] as number) : undefined;

/**
 * Preset → node patch (editor params, SI). Same semantics as the desktop:
 * dimensions and material apply; a cataloged mass becomes a mass override
 * (real parts weigh what they weigh, not what the geometry computes).
 */
export function presetPatch(type: ComponentType, p: Preset): Partial<ComponentNode> {
  const patch: Partial<ComponentNode> = { name: `${p.manufacturer} ${p.partNo}` };
  const half = (v: number | undefined) => (v === undefined ? undefined : v / 2);
  const set = (key: string, v: unknown) => {
    if (v !== undefined && v !== null) (patch as Record<string, unknown>)[key] = v;
  };

  if (p.material?.type === 'BULK') {
    set('materialName', p.material.name);
    set('density', p.material.density);
  }
  if (p.mass !== undefined) set('overrideMass', p.mass);

  const out = n(p, 'outsideDiameter');
  const inn = n(p, 'insideDiameter');
  switch (type) {
    case 'bodytube':
    case 'tubecoupler':
    case 'innertube':
      set('length', n(p, 'length'));
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'nosecone':
      set('length', n(p, 'length'));
      set('aftRadius', half(out));
      set('shape', typeof p['shape'] === 'string' ? (p['shape'] as string).toLowerCase() : undefined);
      if (p['filled'] === true) set('filled', true);
      set('shoulderRadius', half(n(p, 'shoulderDiameter')));
      set('shoulderLength', n(p, 'shoulderLength'));
      set('thickness', n(p, 'thickness'));
      break;
    case 'transition':
      set('length', n(p, 'length'));
      set('foreRadius', half(n(p, 'foreOutsideDiameter')));
      set('aftRadius', half(n(p, 'aftOutsideDiameter')));
      set('shape', typeof p['shape'] === 'string' ? (p['shape'] as string).toLowerCase() : undefined);
      set('foreShoulderRadius', half(n(p, 'foreShoulderDiameter')));
      set('foreShoulderLength', n(p, 'foreShoulderLength'));
      set('aftShoulderRadius', half(n(p, 'aftShoulderDiameter')));
      set('aftShoulderLength', n(p, 'aftShoulderLength'));
      set('thickness', n(p, 'thickness'));
      break;
    case 'centeringring':
    case 'bulkhead':
      set('length', n(p, 'length'));
      break;
    case 'engineblock':
      set('length', n(p, 'length'));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'launchlug':
      set('length', n(p, 'length'));
      set('outerRadius', half(out));
      if (out !== undefined && inn !== undefined) set('thickness', (out - inn) / 2);
      break;
    case 'parachute':
      set('diameter', n(p, 'diameter'));
      set('lineCount', n(p, 'lineCount'));
      set('lineLength', n(p, 'lineLength'));
      if (p.material?.type === 'SURFACE') {
        set('surfaceMaterialName', p.material.name);
        set('surfaceDensity', p.material.density);
      }
      if (p.lineMaterial) {
        set('lineMaterialName', p.lineMaterial.name);
        set('lineDensity', p.lineMaterial.density);
      }
      break;
    case 'streamer':
      set('stripLength', n(p, 'length'));
      set('stripWidth', n(p, 'width'));
      if (p.material?.type === 'SURFACE') {
        set('surfaceMaterialName', p.material.name);
        set('surfaceDensity', p.material.density);
      }
      break;
  }
  return patch;
}

// ---------------- CSV round-trip ----------------

const CSV_COLS = [
  'kind', 'manufacturer', 'partNo', 'description', 'materialName', 'materialType',
  'materialDensity', 'mass', 'length', 'outsideDiameter', 'insideDiameter', 'shape',
  'filled', 'shoulderDiameter', 'shoulderLength', 'thickness', 'foreOutsideDiameter',
  'aftOutsideDiameter', 'foreShoulderDiameter', 'foreShoulderLength',
  'aftShoulderDiameter', 'aftShoulderLength', 'diameter', 'lineCount', 'lineLength', 'width',
];

const csvEscape = (v: unknown): string => {
  const s = v === undefined || v === null ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

export function presetsToCsv(presets: Preset[]): string {
  const rows = [CSV_COLS.join(',')];
  for (const p of presets) {
    const flat: Record<string, unknown> = {
      ...p,
      materialName: p.material?.name,
      materialType: p.material?.type,
      materialDensity: p.material?.density,
    };
    rows.push(CSV_COLS.map((c) => csvEscape(flat[c])).join(','));
  }
  return rows.join('\n') + '\n';
}

function splitCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = '';
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]!;
    if (quoted) {
      if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (ch === '"') quoted = false;
      else cur += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { out.push(cur); cur = ''; }
    else cur += ch;
  }
  out.push(cur);
  return out;
}

/** Parses an edited CSV back into presets (SI values, same columns as export). */
export function csvToPresets(csv: string): Preset[] {
  const lines = csv.split(/\r?\n/).filter((l) => l.trim().length > 0);
  if (lines.length < 2) return [];
  const header = splitCsvLine(lines[0]!).map((h) => h.trim());
  const out: Preset[] = [];
  for (const line of lines.slice(1)) {
    const cells = splitCsvLine(line);
    const row: Record<string, string> = {};
    header.forEach((h, i) => { row[h] = cells[i] ?? ''; });
    if (!row['kind'] || !row['partNo']) continue;
    const p: Preset = {
      kind: row['kind']!,
      manufacturer: row['manufacturer'] || 'Custom',
      partNo: row['partNo']!,
      description: row['description'] ?? '',
    };
    if (row['materialName'] && row['materialDensity']) {
      p.material = {
        name: row['materialName']!,
        type: row['materialType'] || 'BULK',
        density: Number(row['materialDensity']),
      };
    }
    for (const c of CSV_COLS) {
      if (['kind', 'manufacturer', 'partNo', 'description', 'materialName', 'materialType', 'materialDensity', 'shape', 'filled'].includes(c)) continue;
      const v = Number(row[c]);
      if (row[c] !== '' && Number.isFinite(v)) p[c] = v;
    }
    if (row['shape']) p['shape'] = row['shape'];
    if (row['filled'] === 'true') p['filled'] = true;
    out.push(p);
  }
  return out;
}
