import { useEffect, useRef, useState } from 'react';
import type { ComponentNode, ComponentPosition, RocketTree, StaticInfo } from '@online-openrocket/engine';
import { anchorStarts, axialLength, offsetForStart, snapStart, startFromPosition } from '../tree/position.js';

/**
 * 2D side view generated by walking the component tree. Symmetric top-level
 * components (nose/transition/body) form the axial chain; children draw on
 * or inside their parent at their resolved axial position and can be DRAGGED
 * axially (snapping to structural anchors — tube ends, sibling edges).
 * CG/CP markers use standard rocketry symbols.
 */

interface Ctx {
  scale: number;
  cy: number;
  x0: number;
}

const num = (n: ComponentNode, key: string, fb: number): number =>
  typeof n[key] === 'number' ? (n[key] as number) : fb;

const fillOf = (n: ComponentNode, dflt: string): string =>
  typeof n['color'] === 'string' ? (n['color'] as string) : dflt;

/** Tab front edge from the fin's leading edge (AxialMethod.getAsPosition). */
export function finTabFront(n: ComponentNode, finLen: number): number {
  const offset = num(n, 'tabOffset', 0);
  const tabLen = num(n, 'tabLength', 0);
  const method = typeof n['tabOffsetMethod'] === 'string' ? (n['tabOffsetMethod'] as string) : 'middle';
  if (method === 'top') return offset;
  if (method === 'bottom') return offset + (finLen - tabLen);
  return offset + (finLen - tabLen) / 2;
}

function axialStart(child: ComponentNode, childLen: number, pStart: number, pLen: number): number {
  const pos = (child.position ?? { method: 'top', offset: 0 }) as ComponentPosition;
  return pStart + startFromPosition(pos, childLen, pLen);
}

interface DragState {
  childId: string;
  parent: ComponentNode;
  child: ComponentNode;
  pLen: number;
  /** parent-relative start at pointer-down (m) */
  relStart: number;
  pointerX: number;
  /** viewBox px per client px */
  clientScale: number;
}

export function TreeSchematic({ tree, info, onPatchNode }: {
  tree: RocketTree;
  info: StaticInfo | null;
  onPatchNode?: (id: string, patch: Partial<ComponentNode>) => void;
}) {
  const svgRef = useRef<SVGSVGElement>(null);
  const drag = useRef<DragState | null>(null);
  // View transform (zoom & pan) in viewBox px; identity = whole rocket fits.
  const [zoom, setZoom] = useState({ k: 1, x: 0, y: 0 });
  const pan = useRef<{ pointerX: number; pointerY: number; x0: number; y0: number } | null>(null);

  // --- measure the axial chain ---
  let totalLen = 0;
  let maxR = 0.001;
  for (const n of tree.components) {
    if (n.type === 'nosecone' || n.type === 'bodytube' || n.type === 'transition') {
      totalLen += num(n, 'length', 0);
      maxR = Math.max(maxR, num(n, 'aftRadius', 0), num(n, 'outerRadius', 0), num(n, 'foreRadius', 0));
    }
  }
  const finH = Math.max(
    0,
    ...collect(tree.components, (n) =>
      n.type.endsWith('finset') ? num(n, 'height', 0.03) : 0),
  );
  totalLen = Math.max(totalLen, 0.05);

  const w = 640;
  const h = 210;
  const pad = 26;
  const scale = Math.min((w - 2 * pad) / totalLen, (h - 2 * pad) / (2 * (maxR + finH)));
  const ctx: Ctx = { scale, cy: h / 2, x0: pad };

  const beginDrag = (child: ComponentNode, parent: ComponentNode, pLen: number) =>
    (e: React.PointerEvent) => {
      if (!onPatchNode || !child.id) return;
      const rect = svgRef.current?.getBoundingClientRect();
      if (!rect || rect.width === 0) return;
      e.stopPropagation(); // don't also start a background pan
      const pos = (child.position ?? { method: 'top', offset: 0 }) as ComponentPosition;
      drag.current = {
        childId: child.id,
        parent,
        child,
        pLen,
        relStart: startFromPosition(pos, axialLength(child), pLen),
        pointerX: e.clientX,
        clientScale: w / rect.width,
      };
      (e.currentTarget as Element).setPointerCapture?.(e.pointerId);
    };

  const beginPan = (e: React.PointerEvent) => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || rect.width === 0) return;
    pan.current = { pointerX: e.clientX, pointerY: e.clientY, x0: zoom.x, y0: zoom.y };
    (e.currentTarget as Element).setPointerCapture?.(e.pointerId);
  };

  const onMove = (e: React.PointerEvent) => {
    const d = drag.current;
    if (d && onPatchNode) {
      const dxModel = ((e.clientX - d.pointerX) * d.clientScale) / (scale * zoom.k);
      const anchors = anchorStarts(d.parent, d.child);
      const epsilon = (6 * 1) / (scale * zoom.k); // ~6 screen px of magnetism
      const snapped = snapStart(d.relStart + dxModel, anchors, epsilon);
      const pos = (d.child.position ?? { method: 'top', offset: 0 }) as ComponentPosition;
      onPatchNode(d.childId, {
        position: {
          method: pos.method,
          offset: offsetForStart(pos.method, snapped, axialLength(d.child), d.pLen),
        },
      });
      return;
    }
    const p = pan.current;
    if (p) {
      const rect = svgRef.current?.getBoundingClientRect();
      if (!rect || rect.width === 0) return;
      const clientScale = w / rect.width;
      setZoom((z) => ({
        ...z,
        x: p.x0 + (e.clientX - p.pointerX) * clientScale,
        y: p.y0 + (e.clientY - p.pointerY) * clientScale,
      }));
    }
  };

  const endDrag = () => { drag.current = null; pan.current = null; };

  // Wheel zoom around the pointer. Native listener: React's onWheel is
  // passive, so preventDefault (to stop page scroll) must be attached here.
  useEffect(() => {
    const svg = svgRef.current;
    if (!svg) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      const rect = svg.getBoundingClientRect();
      if (rect.width === 0) return;
      const px = ((e.clientX - rect.left) / rect.width) * w;
      const py = ((e.clientY - rect.top) / rect.height) * h;
      setZoom((z) => {
        const k = Math.min(12, Math.max(1, z.k * (e.deltaY < 0 ? 1.2 : 1 / 1.2)));
        if (k === z.k) return z;
        // Keep the model point under the cursor fixed while scaling.
        const mx = (px - z.x) / z.k;
        const my = (py - z.y) / z.k;
        const next = { k, x: px - mx * k, y: py - my * k };
        return k === 1 ? { k: 1, x: 0, y: 0 } : next;
      });
    };
    svg.addEventListener('wheel', onWheel, { passive: false });
    return () => svg.removeEventListener('wheel', onWheel);
  }, []);

  // --- render chain + children ---
  const shapes: React.ReactNode[] = [];
  let x = 0;
  let key = 0;

  const renderChildren = (parent: ComponentNode, pStart: number, pLen: number, pRadius: number) => {
    for (const child of parent.children ?? []) {
      const t = child.type;
      const grab = onPatchNode && child.id
        ? {
          onPointerDown: beginDrag(child, parent, pLen),
          style: { cursor: 'grab' } as React.CSSProperties,
        }
        : {};
      // Through-the-wall fin tab: dashed rect from the body surface inward.
      const renderTab = (finStart: number, finLen: number) => {
        const tabH = Math.min(num(child, 'tabHeight', 0), pRadius);
        const tabLen = num(child, 'tabLength', 0);
        if (tabH <= 0 || tabLen <= 0) return;
        const front = finStart + finTabFront(child, finLen);
        for (const dir of [1, -1] as const) {
          const yTop = dir === 1
            ? ctx.cy + (pRadius - tabH) * ctx.scale
            : ctx.cy - pRadius * ctx.scale;
          shapes.push(
            <rect key={key++} x={ctx.x0 + front * ctx.scale} y={yTop}
              width={Math.max(2, tabLen * ctx.scale)} height={Math.max(1.5, tabH * ctx.scale)}
              fill={fillOf(child, '#b9b7b0')} fillOpacity="0.35"
              stroke="#7a786f" strokeWidth="1" strokeDasharray="3 2"
              style={{ pointerEvents: 'none' }} />,
          );
        }
      };
      if (t === 'freeformfinset') {
        const raw = (child['points'] as [number, number][] | undefined) ?? [];
        if (raw.length >= 3) {
          const chord = Math.max(...raw.map((p) => p[0]));
          const start = axialStart(child, chord, pStart, pLen);
          for (const dir of [1, -1] as const) {
            const ptsStr = raw
              .map(([px, py]) => `${ctx.x0 + (start + px) * ctx.scale},${ctx.cy + dir * (pRadius + py) * ctx.scale}`)
              .join(' ');
            shapes.push(
              <polygon key={key++} points={ptsStr}
                fill={fillOf(child, '#b9b7b0')} stroke="#7a786f" strokeWidth="1" {...grab} />,
            );
          }
          renderTab(start, chord);
        }
      } else if (t === 'trapezoidfinset' || t === 'ellipticalfinset') {
        const root = num(child, 'rootChord', 0.05);
        const tip = t === 'trapezoidfinset' ? num(child, 'tipChord', root * 0.6) : 0;
        const sweep = t === 'trapezoidfinset' ? num(child, 'sweep', 0.02) : root / 2;
        const height = num(child, 'height', 0.03);
        const start = axialStart(child, root, pStart, pLen);
        for (const dir of [1, -1] as const) {
          const y0 = ctx.cy + dir * pRadius * ctx.scale;
          const yh = ctx.cy + dir * (pRadius + height) * ctx.scale;
          const X = ctx.x0 + start * ctx.scale;
          shapes.push(
            t === 'trapezoidfinset' ? (
              <polygon key={key++}
                points={`${X},${y0} ${X + sweep * ctx.scale},${yh} ${X + (sweep + tip) * ctx.scale},${yh} ${X + root * ctx.scale},${y0}`}
                fill={fillOf(child, '#b9b7b0')} stroke="#7a786f" strokeWidth="1" {...grab} />
            ) : (
              <path key={key++}
                d={`M ${X} ${y0} Q ${X + (root / 2) * ctx.scale} ${yh + dir * 4} ${X + root * ctx.scale} ${y0} Z`}
                fill={fillOf(child, '#b9b7b0')} stroke="#7a786f" strokeWidth="1" {...grab} />
            ),
          );
        }
        renderTab(start, root);
      } else if (t === 'launchlug' || t === 'railbutton') {
        const len = num(child, 'length', 0.01);
        const r = num(child, 'outerRadius', 0.002);
        const start = axialStart(child, len, pStart, pLen);
        shapes.push(
          <rect key={key++} x={ctx.x0 + start * ctx.scale}
            y={ctx.cy - (pRadius + 2 * r) * ctx.scale}
            width={Math.max(2, len * ctx.scale)} height={Math.max(2, 2 * r * ctx.scale)}
            fill={fillOf(child, '#c8c5be')} stroke="#7a786f" strokeWidth="1" {...grab} />,
        );
      } else {
        // Internal component: dashed outline inside the parent.
        const len = num(child, 'length', num(child, 'packedLength', 0.025));
        const r = Math.min(
          pRadius * 0.85,
          num(child, 'outerRadius', num(child, 'radius', num(child, 'packedRadius', pRadius * 0.7))),
        );
        const start = axialStart(child, len, pStart, pLen);
        shapes.push(
          <rect key={key++} x={ctx.x0 + start * ctx.scale} y={ctx.cy - r * ctx.scale}
            width={Math.max(2, len * ctx.scale)} height={2 * r * ctx.scale}
            fill="rgba(127,127,127,0.001)" stroke={fillOf(child, '#9a978f')} strokeWidth="1"
            strokeDasharray="3 2" {...grab} />,
        );
        renderChildren(child, start, len, r);
      }
    }
  };

  // Dashed outline for a shoulder sliding inside the adjacent tube.
  const shoulderRect = (startX: number, lenSi: number, rSi: number, color: string) => {
    if (lenSi <= 0 || rSi <= 0) return;
    shapes.push(
      <rect key={key++} x={ctx.x0 + startX * scale} y={ctx.cy - rSi * scale}
        width={Math.max(1.5, lenSi * scale)} height={2 * rSi * scale}
        fill="rgba(127,127,127,0.001)" stroke={color} strokeWidth="1"
        strokeDasharray="3 2" />,
    );
  };

  for (const n of tree.components) {
    const len = num(n, 'length', 0);
    if (n.type === 'nosecone') {
      const r = num(n, 'aftRadius', 0.012);
      shapes.push(<path key={key++} d={nosePath(ctx, x, len, r)} fill={fillOf(n, '#d5d2cb')} stroke="#7a786f" strokeWidth="1" />);
      // Aft shoulder slides into the tube behind the nose.
      shoulderRect(x + len, num(n, 'shoulderLength', 0), num(n, 'shoulderRadius', 0), '#9a978f');
      renderChildren(n, x, len, r);
      x += len;
    } else if (n.type === 'bodytube') {
      const r = num(n, 'outerRadius', 0.012);
      shapes.push(
        <rect key={key++} x={ctx.x0 + x * scale} y={ctx.cy - r * scale}
          width={len * scale} height={2 * r * scale}
          fill={fillOf(n, '#e7e5e0')} stroke="#7a786f" strokeWidth="1" />,
      );
      renderChildren(n, x, len, r);
      x += len;
    } else if (n.type === 'transition') {
      const rf = num(n, 'foreRadius', 0.012);
      const ra = num(n, 'aftRadius', 0.009);
      const X = ctx.x0 + x * scale;
      shapes.push(
        <polygon key={key++}
          points={`${X},${ctx.cy - rf * scale} ${X + len * scale},${ctx.cy - ra * scale} ${X + len * scale},${ctx.cy + ra * scale} ${X},${ctx.cy + rf * scale}`}
          fill={fillOf(n, '#d5d2cb')} stroke="#7a786f" strokeWidth="1" />,
      );
      // Shoulders slide into the tubes ahead of / behind the transition.
      const fsl = num(n, 'foreShoulderLength', 0);
      shoulderRect(x - fsl, fsl, num(n, 'foreShoulderRadius', 0), '#9a978f');
      shoulderRect(x + len, num(n, 'aftShoulderLength', 0), num(n, 'aftShoulderRadius', 0), '#9a978f');
      renderChildren(n, x, len, Math.max(rf, ra));
      x += len;
    }
  }

  const markerR = 9;
  const cgX = info ? ctx.x0 + info.cg * scale : null;
  const cpX = info ? ctx.x0 + info.cp * scale : null;

  return (
    <div style={{ position: 'relative' }}>
      <svg ref={svgRef} viewBox={`0 0 ${w} ${h}`}
          style={{ width: '100%', height: 'auto', display: 'block', touchAction: 'none',
            cursor: zoom.k > 1 ? 'grab' : undefined }}
          role="img" aria-label="Rocket side view with CG and CP markers — drag components, wheel to zoom, drag background to pan"
          onPointerDown={beginPan}
          onPointerMove={onMove} onPointerUp={endDrag} onPointerLeave={endDrag}>
        <g transform={`translate(${zoom.x} ${zoom.y}) scale(${zoom.k})`}>
          {shapes}
          {cgX !== null && (
            <g>
              <circle cx={cgX} cy={ctx.cy} r={markerR} fill="var(--surface-1)" stroke="var(--text-primary)" strokeWidth="1.5" />
              <path d={`M ${cgX} ${ctx.cy} L ${cgX + markerR} ${ctx.cy} A ${markerR} ${markerR} 0 0 1 ${cgX} ${ctx.cy + markerR} Z`} fill="var(--text-primary)" />
              <path d={`M ${cgX} ${ctx.cy} L ${cgX - markerR} ${ctx.cy} A ${markerR} ${markerR} 0 0 1 ${cgX} ${ctx.cy - markerR} Z`} fill="var(--text-primary)" />
              <text x={cgX} y={ctx.cy - markerR - 6} textAnchor="middle" fontSize="11" fill="var(--text-primary)">CG</text>
            </g>
          )}
          {cpX !== null && (
            <g>
              <circle cx={cpX} cy={ctx.cy} r={markerR} fill="none" stroke="#e34948" strokeWidth="2" />
              <circle cx={cpX} cy={ctx.cy} r={3.5} fill="#e34948" />
              <text x={cpX} y={ctx.cy + markerR + 15} textAnchor="middle" fontSize="11" fill="#e34948">CP</text>
            </g>
          )}
        </g>
      </svg>
      {zoom.k > 1 && (
        <button className="file-btn schematic-reset"
          title="Fit the whole rocket in view"
          onClick={() => setZoom({ k: 1, x: 0, y: 0 })}>
          ⤢ Reset view
        </button>
      )}
    </div>
  );
}

function collect<T>(nodes: ComponentNode[], f: (n: ComponentNode) => T): T[] {
  const out: T[] = [];
  const walk = (ns: ComponentNode[]) => {
    for (const n of ns) {
      out.push(f(n));
      walk(n.children ?? []);
    }
  };
  walk(nodes);
  return out;
}

function nosePath(ctx: Ctx, x: number, len: number, r: number): string {
  const X = ctx.x0 + x * ctx.scale;
  const L = len * ctx.scale;
  const R = r * ctx.scale;
  return `M ${X} ${ctx.cy}
    Q ${X + L * 0.15} ${ctx.cy - R * 0.9} ${X + L} ${ctx.cy - R}
    L ${X + L} ${ctx.cy + R}
    Q ${X + L * 0.15} ${ctx.cy + R * 0.9} ${X} ${ctx.cy} Z`;
}
