import type { ComponentNode, ComponentPosition, RocketTree, StaticInfo } from '@online-openrocket/engine';

/**
 * 2D side view generated by walking the component tree. Symmetric top-level
 * components (nose/transition/body) form the axial chain; children draw on
 * or inside their parent at their resolved axial position. CG/CP markers
 * use standard rocketry symbols.
 */

interface Ctx {
  scale: number;
  cy: number;
  x0: number;
}

const num = (n: ComponentNode, key: string, fb: number): number =>
  typeof n[key] === 'number' ? (n[key] as number) : fb;

function axialStart(child: ComponentNode, childLen: number, pStart: number, pLen: number): number {
  const pos = (child.position ?? { method: 'top', offset: 0 }) as ComponentPosition;
  switch (pos.method) {
    case 'middle': return pStart + (pLen - childLen) / 2 + pos.offset;
    case 'bottom': return pStart + pLen - childLen + pos.offset;
    case 'absolute': return pos.offset;
    case 'top':
    default: return pStart + pos.offset;
  }
}

export function TreeSchematic({ tree, info }: { tree: RocketTree; info: StaticInfo | null }) {
  // --- measure the axial chain ---
  let totalLen = 0;
  let maxR = 0.001;
  for (const n of tree.components) {
    if (n.type === 'nosecone' || n.type === 'bodytube' || n.type === 'transition') {
      totalLen += num(n, 'length', 0);
      maxR = Math.max(maxR, num(n, 'aftRadius', 0), num(n, 'outerRadius', 0), num(n, 'foreRadius', 0));
    }
  }
  const finH = Math.max(
    0,
    ...collect(tree.components, (n) =>
      n.type.endsWith('finset') ? num(n, 'height', 0.03) : 0),
  );
  totalLen = Math.max(totalLen, 0.05);

  const w = 640;
  const h = 210;
  const pad = 26;
  const scale = Math.min((w - 2 * pad) / totalLen, (h - 2 * pad) / (2 * (maxR + finH)));
  const ctx: Ctx = { scale, cy: h / 2, x0: pad };

  // --- render chain + children ---
  const shapes: React.ReactNode[] = [];
  let x = 0;
  let key = 0;
  for (const n of tree.components) {
    const len = num(n, 'length', 0);
    if (n.type === 'nosecone') {
      const r = num(n, 'aftRadius', 0.012);
      shapes.push(<path key={key++} d={nosePath(ctx, x, len, r)} fill="#d5d2cb" stroke="#7a786f" strokeWidth="1" />);
      renderChildren(n, x, len, r, ctx, shapes, () => key++);
      x += len;
    } else if (n.type === 'bodytube') {
      const r = num(n, 'outerRadius', 0.012);
      shapes.push(
        <rect key={key++} x={ctx.x0 + x * scale} y={ctx.cy - r * scale}
          width={len * scale} height={2 * r * scale}
          fill="#e7e5e0" stroke="#7a786f" strokeWidth="1" />,
      );
      renderChildren(n, x, len, r, ctx, shapes, () => key++);
      x += len;
    } else if (n.type === 'transition') {
      const rf = num(n, 'foreRadius', 0.012);
      const ra = num(n, 'aftRadius', 0.009);
      const X = ctx.x0 + x * scale;
      shapes.push(
        <polygon key={key++}
          points={`${X},${ctx.cy - rf * scale} ${X + len * scale},${ctx.cy - ra * scale} ${X + len * scale},${ctx.cy + ra * scale} ${X},${ctx.cy + rf * scale}`}
          fill="#d5d2cb" stroke="#7a786f" strokeWidth="1" />,
      );
      renderChildren(n, x, len, Math.max(rf, ra), ctx, shapes, () => key++);
      x += len;
    }
  }

  const markerR = 9;
  const cgX = info ? ctx.x0 + info.cg * scale : null;
  const cpX = info ? ctx.x0 + info.cp * scale : null;

  return (
    <svg viewBox={`0 0 ${w} ${h}`} style={{ width: '100%', height: 'auto', display: 'block' }}
        role="img" aria-label="Rocket side view with CG and CP markers">
      {shapes}
      {cgX !== null && (
        <g>
          <circle cx={cgX} cy={ctx.cy} r={markerR} fill="var(--surface-1)" stroke="var(--text-primary)" strokeWidth="1.5" />
          <path d={`M ${cgX} ${ctx.cy} L ${cgX + markerR} ${ctx.cy} A ${markerR} ${markerR} 0 0 1 ${cgX} ${ctx.cy + markerR} Z`} fill="var(--text-primary)" />
          <path d={`M ${cgX} ${ctx.cy} L ${cgX - markerR} ${ctx.cy} A ${markerR} ${markerR} 0 0 1 ${cgX} ${ctx.cy - markerR} Z`} fill="var(--text-primary)" />
          <text x={cgX} y={ctx.cy - markerR - 6} textAnchor="middle" fontSize="11" fill="var(--text-primary)">CG</text>
        </g>
      )}
      {cpX !== null && (
        <g>
          <circle cx={cpX} cy={ctx.cy} r={markerR} fill="none" stroke="#e34948" strokeWidth="2" />
          <circle cx={cpX} cy={ctx.cy} r={3.5} fill="#e34948" />
          <text x={cpX} y={ctx.cy + markerR + 15} textAnchor="middle" fontSize="11" fill="#e34948">CP</text>
        </g>
      )}
    </svg>
  );
}

function collect<T>(nodes: ComponentNode[], f: (n: ComponentNode) => T): T[] {
  const out: T[] = [];
  const walk = (ns: ComponentNode[]) => {
    for (const n of ns) {
      out.push(f(n));
      walk(n.children ?? []);
    }
  };
  walk(nodes);
  return out;
}

function nosePath(ctx: Ctx, x: number, len: number, r: number): string {
  const X = ctx.x0 + x * ctx.scale;
  const L = len * ctx.scale;
  const R = r * ctx.scale;
  return `M ${X} ${ctx.cy}
    Q ${X + L * 0.15} ${ctx.cy - R * 0.9} ${X + L} ${ctx.cy - R}
    L ${X + L} ${ctx.cy + R}
    Q ${X + L * 0.15} ${ctx.cy + R * 0.9} ${X} ${ctx.cy} Z`;
}

function renderChildren(
  parent: ComponentNode,
  pStart: number,
  pLen: number,
  pRadius: number,
  ctx: Ctx,
  out: React.ReactNode[],
  nextKey: () => number,
) {
  for (const child of parent.children ?? []) {
    const t = child.type;
    if (t === 'freeformfinset') {
      const raw = (child['points'] as [number, number][] | undefined) ?? [];
      if (raw.length >= 3) {
        const chord = Math.max(...raw.map((p) => p[0]));
        const start = axialStart(child, chord, pStart, pLen);
        for (const dir of [1, -1] as const) {
          const ptsStr = raw
            .map(([x, y]) => `${ctx.x0 + (start + x) * ctx.scale},${ctx.cy + dir * (pRadius + y) * ctx.scale}`)
            .join(' ');
          out.push(
            <polygon key={nextKey()} points={ptsStr}
              fill="#b9b7b0" stroke="#7a786f" strokeWidth="1" />,
          );
        }
      }
    } else if (t === 'trapezoidfinset' || t === 'ellipticalfinset') {
      const root = num(child, 'rootChord', 0.05);
      const tip = t === 'trapezoidfinset' ? num(child, 'tipChord', root * 0.6) : 0;
      const sweep = t === 'trapezoidfinset' ? num(child, 'sweep', 0.02) : root / 2;
      const height = num(child, 'height', 0.03);
      const start = axialStart(child, root, pStart, pLen);
      for (const dir of [1, -1] as const) {
        const y0 = ctx.cy + dir * pRadius * ctx.scale;
        const yh = ctx.cy + dir * (pRadius + height) * ctx.scale;
        const X = ctx.x0 + start * ctx.scale;
        out.push(
          t === 'trapezoidfinset' ? (
            <polygon key={nextKey()}
              points={`${X},${y0} ${X + sweep * ctx.scale},${yh} ${X + (sweep + tip) * ctx.scale},${yh} ${X + root * ctx.scale},${y0}`}
              fill="#b9b7b0" stroke="#7a786f" strokeWidth="1" />
          ) : (
            <path key={nextKey()}
              d={`M ${X} ${y0} Q ${X + (root / 2) * ctx.scale} ${yh + dir * 4} ${X + root * ctx.scale} ${y0} Z`}
              fill="#b9b7b0" stroke="#7a786f" strokeWidth="1" />
          ),
        );
      }
    } else if (t === 'launchlug' || t === 'railbutton') {
      const len = num(child, 'length', 0.01);
      const r = num(child, 'outerRadius', 0.002);
      const start = axialStart(child, len, pStart, pLen);
      out.push(
        <rect key={nextKey()} x={ctx.x0 + start * ctx.scale}
          y={ctx.cy - (pRadius + 2 * r) * ctx.scale}
          width={Math.max(2, len * ctx.scale)} height={Math.max(2, 2 * r * ctx.scale)}
          fill="#c8c5be" stroke="#7a786f" strokeWidth="1" />,
      );
    } else {
      // Internal component: dashed outline inside the parent.
      const len = num(child, 'length', num(child, 'packedLength', 0.025));
      const r = Math.min(
        pRadius * 0.85,
        num(child, 'outerRadius', num(child, 'radius', num(child, 'packedRadius', pRadius * 0.7))),
      );
      const start = axialStart(child, len, pStart, pLen);
      out.push(
        <rect key={nextKey()} x={ctx.x0 + start * ctx.scale} y={ctx.cy - r * ctx.scale}
          width={Math.max(2, len * ctx.scale)} height={2 * r * ctx.scale}
          fill="none" stroke="#9a978f" strokeWidth="1" strokeDasharray="3 2" />,
      );
      renderChildren(child, start, len, r, ctx, out, nextKey);
    }
  }
}
