import { useEffect, useRef, useState } from 'react';
import type { ComponentNode, ComponentPosition, RocketTree, StaticInfo } from '@online-openrocket/engine';
import { anchorStarts, axialLength, offsetForStart, snapStart, startFromPosition } from '../tree/position.js';
import { clusterOffsets } from '../tree/cluster.js';
import { tubeFinRadius } from '../tree/tubefins.js';
import { DISPLAY_NAME } from '../tree/schema.js';
import {
  assemblyBoundingRadius, assemblyChainLength, isAssembly,
  resolveAssemblyRadius, ringInstanceOffsets,
} from '../tree/assembly.js';

/**
 * 2D side view generated by walking the component tree. Symmetric top-level
 * components (nose/transition/body) form the axial chain; children draw on
 * or inside their parent at their resolved axial position and can be DRAGGED
 * axially (snapping to structural anchors — tube ends, sibling edges).
 * Clustered inner tubes draw one outline per cluster position.
 * CG/CP markers use standard rocketry symbols.
 */

interface Ctx {
  scale: number;
  cy: number;
  x0: number;
}

const num = (n: ComponentNode, key: string, fb: number): number =>
  typeof n[key] === 'number' ? (n[key] as number) : fb;

const fillOf = (n: ComponentNode, dflt: string): string =>
  typeof n['color'] === 'string' ? (n['color'] as string) : dflt;

/** Tab front edge from the fin's leading edge (AxialMethod.getAsPosition). */
export function finTabFront(n: ComponentNode, finLen: number): number {
  const offset = num(n, 'tabOffset', 0);
  const tabLen = num(n, 'tabLength', 0);
  const method = typeof n['tabOffsetMethod'] === 'string' ? (n['tabOffsetMethod'] as string) : 'middle';
  if (method === 'top') return offset;
  if (method === 'bottom') return offset + (finLen - tabLen);
  return offset + (finLen - tabLen) / 2;
}

function axialStart(child: ComponentNode, childLen: number, pStart: number, pLen: number): number {
  const pos = (child.position ?? { method: 'top', offset: 0 }) as ComponentPosition;
  return pStart + startFromPosition(pos, childLen, pLen);
}

interface DragState {
  childId: string;
  parent: ComponentNode;
  child: ComponentNode;
  pLen: number;
  /** parent-relative start at pointer-down (m) */
  relStart: number;
  pointerX: number;
  /** viewBox px per client px */
  clientScale: number;
}

export function TreeSchematic({ tree, info, motors, onPatchNode, maxHeight = 480 }: {
  tree: RocketTree;
  info: StaticInfo | null;
  /** Loaded motor case dimensions (m) keyed by mount node id — drawn to scale. */
  motors?: Record<string, { length: number; diameter: number }>;
  onPatchNode?: (id: string, patch: Partial<ComponentNode>) => void;
  /** Cap on the drawing's on-screen height (px). */
  maxHeight?: number;
}) {
  const svgRef = useRef<SVGSVGElement>(null);
  const wrapRef = useRef<HTMLDivElement>(null);
  const drag = useRef<DragState | null>(null);
  // Container width (CSS px). The viewBox adopts it 1:1, so the drawing fills
  // the column at native pixel scale on any monitor instead of a fixed 640px
  // canvas stretched to fit.
  const [cw, setCw] = useState(640);
  // View transform (zoom & pan) in viewBox px; identity = whole rocket fits.
  const [zoom, setZoom] = useState({ k: 1, x: 0, y: 0 });
  const pan = useRef<{ pointerX: number; pointerY: number; x0: number; y0: number } | null>(null);

  // --- measure the axial chain ---
  // Stages flatten into one nose-to-tail chain (sustainer first, boosters
  // after — the desktop's stacking order); legacy flat trees pass through.
  const chain = tree.components.flatMap((n) => (n.type === 'stage' ? n.children ?? [] : [n]));
  let totalLen = 0;
  let maxR = 0.001;
  for (const n of chain) {
    if (n.type === 'nosecone' || n.type === 'bodytube' || n.type === 'transition') {
      totalLen += num(n, 'length', 0);
      maxR = Math.max(maxR, num(n, 'aftRadius', 0), num(n, 'outerRadius', 0), num(n, 'foreRadius', 0));
    }
  }
  // A fin set's vertical span: freeform fins carry no 'height' key — their
  // reach is the outline's y-max (the 0.03 default clipped tall freeform fins
  // out of the adaptive-height frame).
  const finSpan = (n: ComponentNode): number => {
    if (!n.type.endsWith('finset')) return 0;
    if (n.type === 'freeformfinset') {
      const pts = n['points'];
      if (Array.isArray(pts) && pts.length > 0) {
        return Math.max(0, ...pts.map((p) => (Array.isArray(p) ? Number(p[1]) || 0 : 0)));
      }
    }
    // Tube fins reach one tube diameter above the body surface.
    if (n.type === 'tubefinset') return 2 * tubeFinRadius(n, maxR);
    return num(n, 'height', 0.03);
  };
  const finH = Math.max(0, ...collect(tree.components, finSpan));
  totalLen = Math.max(totalLen, 0.05);

  // Vertical half-extent (m): the core body + fins, plus any off-axis pod's
  // reach (its centerline radius + its own body + its fins) so pods don't clip.
  let vHalf = maxR + finH;
  const scanRadial = (nodes: ComponentNode[], parentR: number) => {
    for (const n of nodes) {
      if (isAssembly(n.type)) {
        const podFin = Math.max(0, ...collect(n.children ?? [], finSpan));
        vHalf = Math.max(vHalf, resolveAssemblyRadius(n, parentR) + assemblyBoundingRadius(n) + podFin);
        scanRadial(n.children ?? [], assemblyBoundingRadius(n));
      } else {
        const r = Math.max(num(n, 'aftRadius', 0), num(n, 'outerRadius', 0), num(n, 'foreRadius', 0)) || parentR;
        scanRadial(n.children ?? [], r);
      }
    }
  };
  scanRadial(chain, maxR);

  const w = Math.max(320, cw);
  const pad = 26;
  // Height follows the rocket's own proportions (clamped): a long thin
  // rocket gets a wide low band, not a fixed frame of empty sky.
  const h = Math.round(Math.min(maxHeight, Math.max(200, 2 * vHalf * ((w - 2 * pad) / totalLen) + 2 * pad)));
  const scale = Math.min((w - 2 * pad) / totalLen, (h - 2 * pad) / (2 * vHalf));
  const ctx: Ctx = { scale, cy: h / 2, x0: pad };

  const beginDrag = (child: ComponentNode, parent: ComponentNode, pLen: number) =>
    (e: React.PointerEvent) => {
      if (!onPatchNode || !child.id) return;
      const rect = svgRef.current?.getBoundingClientRect();
      if (!rect || rect.width === 0) return;
      e.stopPropagation(); // don't also start a background pan
      const pos = (child.position ?? { method: 'top', offset: 0 }) as ComponentPosition;
      drag.current = {
        childId: child.id,
        parent,
        child,
        pLen,
        relStart: startFromPosition(pos, axialLength(child), pLen),
        pointerX: e.clientX,
        clientScale: w / rect.width,
      };
      (e.currentTarget as Element).setPointerCapture?.(e.pointerId);
    };

  const beginPan = (e: React.PointerEvent) => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || rect.width === 0) return;
    pan.current = { pointerX: e.clientX, pointerY: e.clientY, x0: zoom.x, y0: zoom.y };
    (e.currentTarget as Element).setPointerCapture?.(e.pointerId);
  };

  const onMove = (e: React.PointerEvent) => {
    const d = drag.current;
    if (d && onPatchNode) {
      const dxModel = ((e.clientX - d.pointerX) * d.clientScale) / (scale * zoom.k);
      const anchors = anchorStarts(d.parent, d.child);
      const epsilon = (6 * 1) / (scale * zoom.k); // ~6 screen px of magnetism
      const snapped = snapStart(d.relStart + dxModel, anchors, epsilon);
      const pos = (d.child.position ?? { method: 'top', offset: 0 }) as ComponentPosition;
      onPatchNode(d.childId, {
        position: {
          method: pos.method,
          offset: offsetForStart(pos.method, snapped, axialLength(d.child), d.pLen),
        },
      });
      return;
    }
    const p = pan.current;
    if (p) {
      const rect = svgRef.current?.getBoundingClientRect();
      if (!rect || rect.width === 0) return;
      const clientScale = w / rect.width;
      setZoom((z) => ({
        ...z,
        x: p.x0 + (e.clientX - p.pointerX) * clientScale,
        y: p.y0 + (e.clientY - p.pointerY) * clientScale,
      }));
    }
  };

  const endDrag = () => { drag.current = null; pan.current = null; };

  // Track the container's width so the viewBox can follow it.
  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const obs = new ResizeObserver(() => {
      if (el.clientWidth > 0) setCw(el.clientWidth);
    });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  // Wheel zoom around the pointer. Native listener: React's onWheel is
  // passive, so preventDefault (to stop page scroll) must be attached here.
  useEffect(() => {
    const svg = svgRef.current;
    if (!svg) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      const rect = svg.getBoundingClientRect();
      if (rect.width === 0) return;
      const px = ((e.clientX - rect.left) / rect.width) * w;
      const py = ((e.clientY - rect.top) / rect.height) * h;
      setZoom((z) => {
        const k = Math.min(12, Math.max(1, z.k * (e.deltaY < 0 ? 1.2 : 1 / 1.2)));
        if (k === z.k) return z;
        // Keep the model point under the cursor fixed while scaling.
        const mx = (px - z.x) / z.k;
        const my = (py - z.y) / z.k;
        const next = { k, x: px - mx * k, y: py - my * k };
        return k === 1 ? { k: 1, x: 0, y: 0 } : next;
      });
    };
    svg.addEventListener('wheel', onWheel, { passive: false });
    return () => svg.removeEventListener('wheel', onWheel);
  }, [w, h]);

  // Button zoom steps around the view center (the wheel handles precise
  // pointer-anchored zoom; these make the capability visible).
  const zoomBy = (f: number) => setZoom((z) => {
    const k = Math.min(12, Math.max(1, z.k * f));
    if (k === z.k) return z;
    const mx = (w / 2 - z.x) / z.k;
    const my = (h / 2 - z.y) / z.k;
    return k === 1 ? { k: 1, x: 0, y: 0 } : { k, x: w / 2 - mx * k, y: h / 2 - my * k };
  });

  // --- render chain + children ---
  const shapes: React.ReactNode[] = [];
  // Dashed "shadow" shapes (inner components, shoulders) paint AFTER the whole
  // hull: SVG stacks by document order, so a coupler overhanging into the NEXT
  // tube used to vanish under that tube's opaque fill (while the overhang into
  // the PREVIOUS tube, already painted, stayed visible — Eric's ebay report).
  const overlay: React.ReactNode[] = [];
  let key = 0;

  const renderChildren = (parent: ComponentNode, pStart: number, pLen: number, pRadius: number, baseY: number) => {
    for (const child of parent.children ?? []) {
      const t = child.type;
      // Off-axis assembly: draw its whole chain once per ring instance at the
      // instance's projected baseline (side view projects y, ignores depth z).
      if (isAssembly(t)) {
        const podChain = child.children ?? [];
        const podLen = assemblyChainLength(child);
        const podRadius = resolveAssemblyRadius(child, pRadius);
        const podStart = axialStart(child, podLen, pStart, pLen);
        const count = Math.max(1, Math.round(num(child, 'instanceCount', 2)));
        for (const off of ringInstanceOffsets(count, podRadius, num(child, 'angleOffset', 0))) {
          renderChain(podChain, podStart, baseY + off.y * ctx.scale);
        }
        continue;
      }
      const grab = onPatchNode && child.id
        ? {
          onPointerDown: beginDrag(child, parent, pLen),
          style: { cursor: 'grab' } as React.CSSProperties,
        }
        : {};
      // Through-the-wall fin tab: dashed rect from the body surface inward.
      const renderTab = (finStart: number, finLen: number) => {
        const tabH = Math.min(num(child, 'tabHeight', 0), pRadius);
        const tabLen = num(child, 'tabLength', 0);
        if (tabH <= 0 || tabLen <= 0) return;
        const front = finStart + finTabFront(child, finLen);
        for (const dir of [1, -1] as const) {
          const yTop = dir === 1
            ? baseY + (pRadius - tabH) * ctx.scale
            : baseY - pRadius * ctx.scale;
          shapes.push(
            <rect key={key++} x={ctx.x0 + front * ctx.scale} y={yTop}
              width={Math.max(2, tabLen * ctx.scale)} height={Math.max(1.5, tabH * ctx.scale)}
              fill={fillOf(child, '#b9b7b0')} fillOpacity="0.35"
              stroke="#7a786f" strokeWidth="1" strokeDasharray="3 2"
              style={{ pointerEvents: 'none' }} />,
          );
        }
      };
      if (t === 'freeformfinset') {
        const raw = (child['points'] as [number, number][] | undefined) ?? [];
        if (raw.length >= 3) {
          const chord = Math.max(...raw.map((p) => p[0]));
          const start = axialStart(child, chord, pStart, pLen);
          for (const dir of [1, -1] as const) {
            const ptsStr = raw
              .map(([px, py]) => `${ctx.x0 + (start + px) * ctx.scale},${baseY + dir * (pRadius + py) * ctx.scale}`)
              .join(' ');
            shapes.push(
              <polygon key={key++} points={ptsStr}
                fill={fillOf(child, '#b9b7b0')} stroke="#7a786f" strokeWidth="1" {...grab} />,
            );
          }
          renderTab(start, chord);
        }
      } else if (t === 'trapezoidfinset' || t === 'ellipticalfinset') {
        const root = num(child, 'rootChord', 0.05);
        const tip = t === 'trapezoidfinset' ? num(child, 'tipChord', root * 0.6) : 0;
        const sweep = t === 'trapezoidfinset' ? num(child, 'sweep', 0.02) : root / 2;
        const height = num(child, 'height', 0.03);
        const start = axialStart(child, root, pStart, pLen);
        for (const dir of [1, -1] as const) {
          const y0 = baseY + dir * pRadius * ctx.scale;
          const yh = baseY + dir * (pRadius + height) * ctx.scale;
          const X = ctx.x0 + start * ctx.scale;
          shapes.push(
            t === 'trapezoidfinset' ? (
              <polygon key={key++}
                points={`${X},${y0} ${X + sweep * ctx.scale},${yh} ${X + (sweep + tip) * ctx.scale},${yh} ${X + root * ctx.scale},${y0}`}
                fill={fillOf(child, '#b9b7b0')} stroke="#7a786f" strokeWidth="1" {...grab} />
            ) : (
              <path key={key++}
                d={`M ${X} ${y0} Q ${X + (root / 2) * ctx.scale} ${yh + dir * 4} ${X + root * ctx.scale} ${y0} Z`}
                fill={fillOf(child, '#b9b7b0')} stroke="#7a786f" strokeWidth="1" {...grab} />
            ),
          );
        }
        renderTab(start, root);
      } else if (t === 'tubefinset') {
        // Side view: the top and bottom tubes of the ring, sitting on the
        // body surface (side tubes project onto the body — omitted). Each
        // is drawn as its silhouette rectangle with a center line hinting
        // at the tube bore.
        const len = num(child, 'length', 0.1);
        const rt = tubeFinRadius(child, pRadius);
        const start = axialStart(child, len, pStart, pLen);
        const X = ctx.x0 + start * ctx.scale;
        for (const dir of [1, -1] as const) {
          const yNear = baseY + dir * pRadius * ctx.scale;
          const yFar = baseY + dir * (pRadius + 2 * rt) * ctx.scale;
          shapes.push(
            <rect key={key++} x={X} y={Math.min(yNear, yFar)}
              width={Math.max(2, len * ctx.scale)} height={Math.abs(yFar - yNear)}
              rx="2" fill={fillOf(child, '#c8c5be')} fillOpacity="0.6"
              stroke="#7a786f" strokeWidth="1" {...grab} />,
            <line key={key++} x1={X} y1={(yNear + yFar) / 2} x2={X + len * ctx.scale} y2={(yNear + yFar) / 2}
              stroke="#7a786f" strokeWidth="0.8" strokeDasharray="4 3"
              style={{ pointerEvents: 'none' }} />,
          );
        }
      } else if (t === 'launchlug' || t === 'railbutton') {
        // Rail buttons are edited via 'outerDiameter' (their only size field)
        // and have no axial 'length' — a button is about as long as it is wide.
        const btnDia = t === 'railbutton' ? num(child, 'outerDiameter', 0.004) : 0;
        const len = t === 'railbutton' ? btnDia : num(child, 'length', 0.01);
        const r = t === 'railbutton' ? btnDia / 2 : num(child, 'outerRadius', 0.002);
        const start = axialStart(child, len, pStart, pLen);
        shapes.push(
          <rect key={key++} x={ctx.x0 + start * ctx.scale}
            y={baseY - (pRadius + 2 * r) * ctx.scale}
            width={Math.max(2, len * ctx.scale)} height={Math.max(2, 2 * r * ctx.scale)}
            fill={fillOf(child, '#c8c5be')} stroke="#7a786f" strokeWidth="1" {...grab} />,
        );
      } else {
        // Internal component: dashed outline inside the parent. A clustered
        // inner tube draws once per cluster position (side-view projection).
        // Per-type stroke color + a small tag differentiate what used to be
        // identical grey boxes (issue 2026-08-05a #21) — tubes/couplers stay
        // neutral (they really are tube segments), payload-type parts get
        // muted colors from the theme-safe midrange.
        const TYPE_STYLE: Partial<Record<string, { stroke: string; tag: string }>> = {
          parachute: { stroke: '#b06a35', tag: 'chute' },
          streamer: { stroke: '#a08c2e', tag: 'strmr' },
          shockcord: { stroke: '#8f7a8d', tag: 'cord' },
          masscomponent: { stroke: '#a85f5c', tag: 'mass' },
          centeringring: { stroke: '#6f8a5c', tag: 'CR' },
          bulkhead: { stroke: '#66748c', tag: 'BH' },
          engineblock: { stroke: '#7d7050', tag: 'EB' },
        };
        const style = TYPE_STYLE[child.type];
        const len = num(child, 'length', num(child, 'packedLength', 0.025));
        const r = Math.min(
          pRadius * 0.85,
          num(child, 'outerRadius', num(child, 'radius', num(child, 'packedRadius', pRadius * 0.7))),
        );
        const start = axialStart(child, len, pStart, pLen);
        const offsets = child.type === 'innertube'
          ? clusterOffsets(
            child['cluster'] as string | undefined,
            num(child, 'outerRadius', 0.0095),
            num(child, 'clusterScale', 1),
            num(child, 'clusterRotation', 0),
          )
          : [{ y: 0, z: 0 }];
        // Loaded motor: a brownish silhouette at the REAL case size, seated
        // flush against the mount's aft end (how motors actually load).
        const motor = child.type === 'innertube' && child.id ? motors?.[child.id] : undefined;
        for (const off of offsets) {
          overlay.push(
            <rect key={key++} x={ctx.x0 + start * ctx.scale}
              y={baseY + (off.y - r) * ctx.scale}
              width={Math.max(2, len * ctx.scale)} height={2 * r * ctx.scale}
              fill="rgba(127,127,127,0.001)"
              stroke={fillOf(child, style?.stroke ?? '#9a978f')} strokeWidth="1"
              strokeDasharray="3 2" {...grab}>
              <title>{child.name ?? DISPLAY_NAME[child.type]}</title>
            </rect>,
          );
          // Type tag, when the box has room for it.
          if (style && len * ctx.scale > 26 && 2 * r * ctx.scale > 11) {
            overlay.push(
              <text key={key++}
                x={ctx.x0 + (start + len / 2) * ctx.scale}
                y={baseY + off.y * ctx.scale}
                textAnchor="middle" dominantBaseline="central"
                fontSize="8.5" fill={fillOf(child, style.stroke)}
                style={{ pointerEvents: 'none', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                {style.tag}
              </text>,
            );
          }
          if (motor) {
            const mR = motor.diameter / 2;
            const mStart = start + len - motor.length + num(child, 'motorOverhang', 0);
            overlay.push(
              <rect key={key++} x={ctx.x0 + mStart * ctx.scale}
                y={baseY + (off.y - mR) * ctx.scale}
                width={Math.max(2, motor.length * ctx.scale)} height={Math.max(2, 2 * mR * ctx.scale)}
                rx="1" fill="#8b5a2b" fillOpacity="0.45"
                stroke="#6b4520" strokeWidth="0.8"
                style={{ pointerEvents: 'none' }} />,
            );
          }
        }
        renderChildren(child, start, len, r, baseY);
      }
    }
  };

  // Dashed outline for a shoulder sliding inside the adjacent tube. Painted in
  // the overlay pass — an aft shoulder lives inside the NEXT tube, which is
  // drawn later and would otherwise cover it.
  const shoulderRect = (startX: number, lenSi: number, rSi: number, color: string, baseY: number) => {
    if (lenSi <= 0 || rSi <= 0) return;
    overlay.push(
      <rect key={key++} x={ctx.x0 + startX * scale} y={baseY - rSi * scale}
        width={Math.max(1.5, lenSi * scale)} height={2 * rSi * scale}
        fill="rgba(127,127,127,0.001)" stroke={color} strokeWidth="1"
        strokeDasharray="3 2" />,
    );
  };

  // Draws an axial nose→tail chain with its centerline at screen `baseY`
  // (ctx.cy for the core rocket; offset for each off-axis pod instance).
  const renderChain = (nodes: ComponentNode[], xStart: number, baseY: number) => {
    let cx = xStart;
    for (const n of nodes) {
      const len = num(n, 'length', 0);
      if (n.type === 'nosecone') {
        const r = num(n, 'aftRadius', 0.012);
        shapes.push(<path key={key++} d={nosePath(ctx, cx, len, r, baseY)} fill={fillOf(n, '#d5d2cb')} stroke="#7a786f" strokeWidth="1" />);
        shoulderRect(cx + len, num(n, 'shoulderLength', 0), num(n, 'shoulderRadius', 0), '#9a978f', baseY);
        renderChildren(n, cx, len, r, baseY);
        cx += len;
      } else if (n.type === 'bodytube') {
        const r = num(n, 'outerRadius', 0.012);
        shapes.push(
          <rect key={key++} x={ctx.x0 + cx * scale} y={baseY - r * scale}
            width={len * scale} height={2 * r * scale}
            fill={fillOf(n, '#e7e5e0')} stroke="#7a786f" strokeWidth="1" />,
        );
        // Min-diameter: a motor loaded directly in this body tube draws at its
        // real case size, seated flush against the tube's aft end.
        const tubeMotor = n.id ? motors?.[n.id] : undefined;
        if (tubeMotor) {
          const mR = tubeMotor.diameter / 2;
          const mStart = cx + len - tubeMotor.length + num(n, 'motorOverhang', 0);
          shapes.push(
            <rect key={key++} x={ctx.x0 + mStart * scale}
              y={baseY - mR * scale}
              width={Math.max(2, tubeMotor.length * scale)} height={Math.max(2, 2 * mR * scale)}
              rx="1" fill="#8b5a2b" fillOpacity="0.45"
              stroke="#6b4520" strokeWidth="0.8"
              style={{ pointerEvents: 'none' }} />,
          );
        }
        renderChildren(n, cx, len, r, baseY);
        cx += len;
      } else if (n.type === 'transition') {
        const rf = num(n, 'foreRadius', 0.012);
        const ra = num(n, 'aftRadius', 0.009);
        const X = ctx.x0 + cx * scale;
        shapes.push(
          <polygon key={key++}
            points={`${X},${baseY - rf * scale} ${X + len * scale},${baseY - ra * scale} ${X + len * scale},${baseY + ra * scale} ${X},${baseY + rf * scale}`}
            fill={fillOf(n, '#d5d2cb')} stroke="#7a786f" strokeWidth="1" />,
        );
        const fsl = num(n, 'foreShoulderLength', 0);
        shoulderRect(cx - fsl, fsl, num(n, 'foreShoulderRadius', 0), '#9a978f', baseY);
        shoulderRect(cx + len, num(n, 'aftShoulderLength', 0), num(n, 'aftShoulderRadius', 0), '#9a978f', baseY);
        renderChildren(n, cx, len, Math.max(rf, ra), baseY);
        cx += len;
      }
    }
  };

  renderChain(chain, 0, ctx.cy);

  const markerR = 9;
  const cgX = info ? ctx.x0 + info.cg * scale : null;
  const cpX = info ? ctx.x0 + info.cp * scale : null;

  return (
    <div ref={wrapRef} style={{ position: 'relative' }}>
      <svg ref={svgRef} viewBox={`0 0 ${w} ${h}`}
          style={{ width: '100%', height: 'auto', display: 'block', touchAction: 'none',
            cursor: zoom.k > 1 ? 'grab' : undefined }}
          role="img" aria-label="Rocket side view with CG and CP markers — drag components, wheel to zoom, drag background to pan"
          onPointerDown={beginPan}
          onPointerMove={onMove} onPointerUp={endDrag} onPointerLeave={endDrag}>
        <g transform={`translate(${zoom.x} ${zoom.y}) scale(${zoom.k})`}>
          {shapes}
          {overlay}
          {cgX !== null && (
            <g>
              <circle cx={cgX} cy={ctx.cy} r={markerR} fill="var(--surface-1)" stroke="var(--text-primary)" strokeWidth="1.5" />
              <path d={`M ${cgX} ${ctx.cy} L ${cgX + markerR} ${ctx.cy} A ${markerR} ${markerR} 0 0 1 ${cgX} ${ctx.cy + markerR} Z`} fill="var(--text-primary)" />
              <path d={`M ${cgX} ${ctx.cy} L ${cgX - markerR} ${ctx.cy} A ${markerR} ${markerR} 0 0 1 ${cgX} ${ctx.cy - markerR} Z`} fill="var(--text-primary)" />
              <text x={cgX} y={ctx.cy - markerR - 6} textAnchor="middle" fontSize="11" fill="var(--text-primary)">CG</text>
            </g>
          )}
          {cpX !== null && (
            <g>
              <circle cx={cpX} cy={ctx.cy} r={markerR} fill="none" stroke="#e34948" strokeWidth="2" />
              <circle cx={cpX} cy={ctx.cy} r={3.5} fill="#e34948" />
              <text x={cpX} y={ctx.cy + markerR + 15} textAnchor="middle" fontSize="11" fill="#e34948">CP</text>
            </g>
          )}
        </g>
      </svg>
      <div className="schematic-controls">
        {(zoom.k > 1 || zoom.x !== 0 || zoom.y !== 0) && (
          <button className="file-btn"
            title="Fit the whole rocket in view"
            onClick={() => setZoom({ k: 1, x: 0, y: 0 })}>
            ⤢ Fit
          </button>
        )}
        <button className="file-btn" title="Zoom in — or scroll on the drawing; drag to pan"
          aria-label="Zoom in" onClick={() => zoomBy(1.5)} disabled={zoom.k >= 12}>+</button>
        <button className="file-btn" title="Zoom out"
          aria-label="Zoom out" onClick={() => zoomBy(1 / 1.5)} disabled={zoom.k <= 1}>−</button>
      </div>
    </div>
  );
}

function collect<T>(nodes: ComponentNode[], f: (n: ComponentNode) => T): T[] {
  const out: T[] = [];
  const walk = (ns: ComponentNode[]) => {
    for (const n of ns) {
      out.push(f(n));
      walk(n.children ?? []);
    }
  };
  walk(nodes);
  return out;
}

function nosePath(ctx: Ctx, x: number, len: number, r: number, baseY: number): string {
  const X = ctx.x0 + x * ctx.scale;
  const L = len * ctx.scale;
  const R = r * ctx.scale;
  return `M ${X} ${baseY}
    Q ${X + L * 0.15} ${baseY - R * 0.9} ${X + L} ${baseY - R}
    L ${X + L} ${baseY + R}
    Q ${X + L * 0.15} ${baseY + R * 0.9} ${X} ${baseY} Z`;
}
